### ISSUE TITLE
希望对自签名证书进行支持

### ISSUE THREAD

**Issue by yangon99** [project-openwrt/luci-app-unblockneteasemusic#15]
自己本地签名了一个证书并放到了插件的 “/core” 目录下进行了替换，但是发现插件更新核心后，自签名证书也会直接被替换掉。
不知道能否对自签名证书进行支持，例如能够上传自签名证书，或者在更新内核时保存当前证书之类。

**Comment by 1715173329** [comment]
@yangon99 了解，会在近期进行修改。

**Comment by 1715173329** [comment]
现在您可以将证书存放在除 core 文件夹以外的其他位置，并在LuCI中指向它们
