### ISSUE TITLE
更新核心页面炸了

### ISSUE THREAD

**Issue by YujiaCheng1996** [project-openwrt/luci-app-unblockneteasemusic#16]
升级安装的，luci页面打不开提示：
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/unblockneteasemusic/upgrade_core'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:38: Model 'unblockneteasemusic_upcore' not found!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

卸载重装旧版正常，卸载重装新版就报错。

**Comment by 1715173329** [comment]
@YujiaCheng1996 重启或者运行 rm -rf /tmp/luci-*

**Comment by YujiaCheng1996** [comment]
解决了，是缓存的问题。
