### ISSUE TITLE
v2.8-3 更新后 大雕 openwrt 中的bug

### ISSUE THREAD

**Issue by KleinerSource** [project-openwrt/luci-app-unblockneteasemusic#18]
更新了新版之后  启用/禁用插件  插件状态不会变化
(启用>提交后 停止插件不会启动/停用>启提交后 运行的插件不会停止) 
要重启路由才生效

**Comment by 1715173329** [comment]
ipk在打包的时候出了点问题，现在已经重新上传了，你重新安装下试试

**Comment by KleinerSource** [comment]
依旧如此 我当前版本已经更新到 2.8-3了

**Comment by 1715173329** [comment]
@KleinerSource 先卸载再安装🙃

**Comment by KleinerSource** [comment]
卸载再安装就可以了 2333
