### ISSUE TITLE
在旁路由模式下 手机网易云杀掉进程后不能解锁的问题

### ISSUE THREAD

**Issue by 1-github-1** [project-openwrt/luci-app-unblockneteasemusic#19]
在主路由的情况下貌似没这个问题，主要是旁路由模式下会出现这样的情况，安装完成第一次打开都是能解锁的，但是当杀掉这个进程或者手机重启之后就照常显示灰色，需要在wifi那里设置一下代理才行，不知道大家有没有遇到过这个问题

**Comment by 1715173329** [comment]
旁路使用lean插件套娃即可。
