### ISSUE TITLE
需要libopenssl1.1，可是源里没有这个依赖，大佬能提供一个MT7621的依赖么？

### ISSUE THREAD

**Issue by luovivi** [project-openwrt/luci-app-unblockneteasemusic#21]
找到了这个依赖，libopenssl1.1_1.1.1f-1_mipsel_24kc.ipk，可是提示架构不符。可能需要1004kc版本的。

**Comment by AmadeusGhost** [comment]
`opkg update`后再`opkg install libopenssl`

**Comment by luovivi** [comment]
update也不行，自带源只有1.02版本，openwrt官网1.1版本的却没有mipsel_1004kc架构

**Comment by ElonH** [comment]
@luovivi 那就自己编译

**Comment by AmadeusGhost** [comment]
`mipsel_1004kc`是潘多拉的，换openwrt可解

**Comment by 1715173329** [comment]
使用跳过依赖检查即可

**Comment by AmadeusGhost** [comment]
建议付费去找lintel让他帮你定制一个

**Comment by luovivi** [comment]
找到了另一个版本的luci客户端，可以用了，核心应该都一样吧。感谢各位大佬回复
