### ISSUE TITLE
[WARNING] Please take care

### ISSUE THREAD

**Issue by MiaoDX** [project-openwrt/luci-app-unblockneteasemusic#23]
Hi,

Happen to encounter your project, have not checked. Today [Pandownload] dev is caught, please take care of yourself.

Good luck,
MiaoDX

**Comment by 1715173329** [comment]
Dear MiaoDX,

Thank you for your care.

However, it's unnecessary to feel worry about the project [\(UnblockNeteaseMusic\)](https://github.com/nondanee/UnblockNeteaseMusic).
Actually Netease knows this already in early, but takes no action.
Relative to Baidu, they have much better inclusiveness.

So, just feel free to use it.

Project OpenWrt developer,
CN_SZTL.
