### ISSUE TITLE
运行出错!

### ISSUE THREAD

**Issue by snakwu** [project-openwrt/luci-app-unblockneteasemusic#24]
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN 192.168.88.1/24
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1493:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:17) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: '192.168.88.1/24'
}

**Comment by snakwu** [comment]
编译的是x86_64固件

**Comment by AmadeusGhost** [comment]
官方luci天天大改，出错正常

**Comment by snakwu** [comment]
> 官方luci天天大改，出错正常

这个错误应该是核心文件的问题吗？

**Comment by 1715173329** [comment]
DNS 解析一类有问题。

**Comment by snakwu** [comment]
> DNS 解析一类有问题。

大佬，我这还有救吗？
