### ISSUE TITLE
在最新的	5.4.34内核下，显示Insufficient permissions to read UCI configuration.

### ISSUE THREAD

**Issue by zcy85611** [project-openwrt/luci-app-unblockneteasemusic#25]
最近编译了官网最新的master分支，内核升级到5.4.34，其他软件都正常，但是解锁的luci无法正常显示，提示Insufficient permissions to read UCI configuration，请问一下这个应该如何解决？

**Comment by zcy85611** [comment]
路由器是歌华链的GHL-R-001

**Comment by AmadeusGhost** [comment]
你可以试试用https://github.com/project-openwrt/openwrt/tree/18.06-kernel5.4编译
