### ISSUE TITLE
LEDE 2.35无法正常启动

### ISSUE THREAD

**Issue by huojicache** [project-openwrt/luci-app-unblockneteasemusic#29]
手动在ssh中启动提示 out of range

上次安装很正常,今天重置LEDE后重装就出现这个,不知问题出哪里了
另一个问题安装后不能正常获得luci权限,发现获取权限文件不能正常安装进对应目录,
手动拷贝进去后可以正常获取权限(包括上次安装也是手动拷贝的)

**Comment by yizhilaohuli** [comment]
请提供具体形象的错误信息 包括但不限于：录屏、截图、日志 。 
OpenWrt-koolshare-mod 2.35 建议你同时联系koolshare论坛里的作者了解这个插件是否可以在他的固件上正常安装稳定运行。
插件是可以正常稳定在https://github.com/project-openwrt/openwrt 源码编译的固件上运行的。
你是软路由建议你可以考虑一下更换固件以达到稳定使用的体验。

**Comment by 1715173329** [comment]
I won't give any support to KoolShare user.
