### ISSUE TITLE
建议打开公网的时候能够加上账号和密码

### ISSUE THREAD

**Issue by z1790** [project-openwrt/luci-app-unblockneteasemusic#33]
建议打开公网的时候能够加上账号和密码

**Comment by 1715173329** [comment]
@z1790 ？你是说 http 认证？
组件带的那个认证功能是残的，开了也没用

**Comment by SpeedPartner** [comment]
应该找原项目作者提,不过对方早就回答过了
[UnblockNeteaseMusic #43](https://github.com/nondanee/UnblockNeteaseMusic/issues/301)
