### ISSUE TITLE
获取自定义cookie方法告知下

### ISSUE THREAD

**Issue by bike3097a** [project-openwrt/luci-app-unblockneteasemusic#34]
怎么获取自定义kookie呀？
![Screenshot_20201008_072623_com android chrome](https://user-images.githubusercontent.com/72074704/95398226-dcf7a300-0937-11eb-95e3-0a71f207a54e.jpg)

**Comment by 1715173329** [comment]
需要什么值已经告诉你了，至于告诉你怎么获取那是谷歌的义务。
