### ISSUE TITLE
openclash fake-ip模式导致解锁失效

### ISSUE THREAD

**Issue by qin9125** [project-openwrt/luci-app-unblockneteasemusic#39]
求问一下，用到了哪些域名，我该怎么做？才能在open clash fake-ip模式使用，不会出现一段时间后解锁失效。

**Comment by 1715173329** [comment]
本插件与 OpenClash 完全兼容，大量长期测试未发现你所述问题

**Comment by qin9125** [comment]
> 本插件与 OpenClash 完全兼容，大量长期测试未发现你所述问题

谢谢回复，弄混了，这个插件有好几个，我是koolshare的固件装您的这个解锁插件装完后去界面提示uci权限不足重启也不行，装了另一个https://github.com/cnsilvan/luci-app-unblockneteasemusic，会提示uci但是重启可以进入界面，我是要换固件才能安装吗？这个固件基本很多插件都提示uci权限但重启就可以了，唯独您的这个解锁插件重启不行还是提示uci，

**Comment by 1715173329** [comment]
KoolShare 垃圾固件可拉倒吧

有个 workaround，你自己试试吧
在 `/usr/share/rpcd/acl.d/luci-base.json` 开头增加这一段
 ```json
"uci-access": {
  "description": "Grant uci write access to all configurations",
  "read": {
   "uci": [ "*" ]
  },
  "write": {
   "uci": [ "*" ]
  }
 },
```

**Comment by qin9125** [comment]
> KoolShare 垃圾固件可拉倒吧
> 
> 有个 workaround，你自己试试吧
> 在 `/usr/share/rpcd/acl.d/luci-base.json` 开头增加这一段
> 
> ```json
> "uci-access": {
>  "description": "Grant uci write access to all configurations",
>  "read": {
>   "uci": [ "*" ]
>  },
>  "write": {
>   "uci": [ "*" ]
>  }
> },
> ```

哈哈哈，😂，谢谢我试试，我也不想用这个固件，实力不到家又不喜欢用多插件的固件，mac连接路由要ftp，没有像window那样scp图形化软件winscp，纯净固件安装ftp搞配置我都弄不懂，搞半天不行，我就凑合这个固件
