### ISSUE TITLE
TypeError: Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by FR-Chelsea** [project-openwrt/luci-app-unblockneteasemusic#40]
/usr/share/unblockneteasemusic/core/src/app.js:59
const target = Array.from(hook.target.host)
                                      ^

TypeError: Cannot read property 'host' of undefined

**Comment by 1715173329** [comment]
组件下载不完整，删掉重下

**Comment by FR-Chelsea** [comment]
> 组件下载不完整，删掉重下

好的 现在就试试

**Comment by FR-Chelsea** [comment]
> 组件下载不完整，删掉重下

已经好了，删除了所有/usr/share/目录下的unblockneteasemusic 三个目录 重新安装好了
