### ISSUE TITLE
openclash fake-ip

### ISSUE THREAD

**Issue by qin9125** [project-openwrt/luci-app-unblockneteasemusic#41]
感谢您的指点，插件我安装成功并运行了，还是上个issues的提到的问题，是固件问题还是我的规则有问题，跟另外一个解锁插件一样，在fake-ip模式下听歌一会就失效了无法播放，歌曲变灰色，关闭openclash再次打开播放器解锁成功，只有redir-host模式不会发生这样的情况，大佬给个意见怎么搞一下？谢谢
![image](https://user-images.githubusercontent.com/32502941/100905212-c4a0a080-3502-11eb-8879-cb3cf4d3e683.png)

**Comment by 1715173329** [comment]
换固件

**Comment by qin9125** [comment]
> 换固件

推荐个固件喽，大佬，我去换了试试

**Comment by qin9125** [comment]
> 换固件

刷机了一天，试了好几个固件，甚至lean固件自带的网易解锁插件，在开启openclash-fake-ip模式的时候照样会丢失解锁，

**Comment by pikachullk** [comment]
> > 换固件
> 
> 刷机了一天，试了好几个固件，甚至lean固件自带的网易解锁插件，在开启openclash-fake-ip模式的时候照样会丢失解锁，

openclash>全局设置>DNS设置>高级设置>启用>保存设置>点击DNS高级设置下面的检查更新~此贴完结

**Comment by kaiser20106** [comment]
> 

有没有图，openclash界面变化太大了，找不到这个了
