### ISSUE TITLE
IOS能解析出歌曲，但是下载不了

### ISSUE THREAD

**Issue by mjyhj** [project-openwrt/luci-app-unblockneteasemusic#43]
![1](https://user-images.githubusercontent.com/22577418/103554914-9ee42e00-4eea-11eb-943a-0e326cb1eec2.jpg)
![2](https://user-images.githubusercontent.com/22577418/103554922-a1df1e80-4eea-11eb-98fa-5d4f2a49267f.jpg)
一直卡着，正在计算大小
IOS:14.3
网易云：8.0.21
有没一样的

**Comment by 1715173329** [comment]
However it works on my machine,
and I'm not interested in such a closed-source system so there's no progress for the issue.
