### ISSUE TITLE
无法设置HTTPS端口为空(不指定第二个端口)

### ISSUE THREAD

**Issue by SpeedPartner** [project-openwrt/luci-app-unblockneteasemusic#44]
首先当然是要感谢大佬为OpenWrt做了这个配置高度自定义的可视化luci插件>w<

我的Issue是第本插件二个HTTPS端口无法设置为空,如果设置为"0",启动则报错:端口必须在0到65535之间.

原项目不指定端口的话,会默认单个端口8080启动,并且不会配置第二个HTTPS端口,这样就可以使用endpoint到自己域名的HTTPS网站来做反代.

示例:
本人在OpenWrt上搭了个HTTPS站点,由于家用宽带被封80,8080,443常用网页端口,使用的Ngnix监听的4443端口,并设置反代到本插件默认端口localhost:5200.

使用以下单端口命令启动:
`node /usr/share/unblockneteasemusic/core/app.js -s -e https://MyDomian:4443 -p 5200`

可以给IOS和Windows用解锁和播放音乐(安卓能解锁但不能播放,不过我有Xposed模块).

总结:
希望大佬可以设置一个HTTPS(第二个端口)的开关,判断关闭时使用下面命令启动(删掉`:${https_port}`);
或者加个判断,设置"0"或者为"Null"后,判断并使用下面命令启动(删掉`:${https_port}`).
也就是:
`nohup node "/usr/share/$NAME/core/app.js" -a "${addr}" -p "${http_port}":"${https_port}" ${music_source} -e "${endpoint_url}" ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >> "/tmp/$NAME.log" 2>&1 &`
_*目前我是改成上面的命令了*_

当然,要是能做两个配置页面,分别运行两个实例就更好了,这样就三端通吃啦~

**Comment by 1715173329** [comment]
其实无需做所谓反代
http endpoint 应该适用于包括 UWP 在内的所有平台

iOS 方面，我在旧版网易云音乐（7.0.30）测试是完全可用的
新版本也许需要将 endpoint 调整为 https://music.163.com，不过会破坏对 UWP 的兼容。

**Comment by SpeedPartner** [comment]
IOS新版本网易云音乐确实要用HTTPS了.

我主要使用IOS设备远程在外面使用.

endpoint到  https://music.163.com 非常不稳定,只能用WLAN的手动全局代理,PAC自动代理直接废了,播放不了,所以配合ShadowRocket规则也没用.

endpoint到 https://MyDomian 就很优雅,响应速度感觉比自签证书快多了,使用PAC和ShadowRocket规则都没问题,且兼容Windows客户端,客户设备上也免除了信任自签CA证书的步骤.

**Comment by 1715173329** [comment]
我不是很清楚如果你想从外部连接该如何操作

本插件主要为局域网下设备设计，目前还算正常
外部连接这种应该是服务器才需要考虑的，而这不是为服务器写的插件
