### ISSUE TITLE
iPv6公网代理无效

### ISSUE THREAD

**Issue by Koukotsukan** [project-openwrt/luci-app-unblockneteasemusic#9]
有用过另一个作者的同类软件，他那个外网直接代理全部路由器流量了，您的作品是公网连接不能代理通过网易云音乐的流量，我尝试看了proxy.pac发现是直接返回到192.168.1.1:5200(路由器iP)，不知道和这个有没有关系，请求帮助，谢谢您！

**Comment by 1715173329** [comment]
@Koukotsukan “公网连接”具体是指什么

**Comment by Koukotsukan** [comment]
@1715173329 用有IPv6地址的4G网络里在APN添加代理，使用路由器的IPv6地址和插件开放的端口。

**Comment by 1715173329** [comment]
@Koukotsukan 本插件默认未打开ipv6端口
请手动运行ip6tables命令打开端口

**Comment by Koukotsukan** [comment]
收到，我去试试

**Comment by 1715173329** [comment]
该问题已在 6120d20 中得到修正。

**Comment by Koukotsukan** [comment]
感谢！能不能顺便问一下怎么编译成ipk，不懂啊，网上查到的都是编译到op包里面

**Comment by 1715173329** [comment]
@Koukotsukan 下载release即可

**Comment by Koukotsukan** [comment]
妈呀！！！我要是女的我就嫁给你真的。。不扯啦，祝您生活开心！

**Comment by 1715173329** [comment]
@Koukotsukan 生活愉快（🌚

**Comment by Koukotsukan** [comment]
我又回来了，我测试了一下还是不行呀
<a href="https://sm.ms/image/kKYHWRCufDEr6iN" target="_blank"><img src="https://i.loli.net/2019/12/01/kKYHWRCufDEr6iN.png" ></a>

局域网内IPv6也不能访问这个proxy.pac，但是192.168.x.1/proxy.pac可以，不知道原因

**Comment by Koukotsukan** [comment]
我又回来了，我测试了一下还是不行呀
<a href="https://sm.ms/image/gPCkVmyhYe9xw1D" target="_blank"><img src="https://i.loli.net/2019/12/01/gPCkVmyhYe9xw1D.png" ></a>

局域网内IPv6也不能访问这个proxy.pac，但是192.168.x.1/proxy.pac可以，不知道原因

**Comment by 1715173329** [comment]
忘了一件事情。。
UnblockNeteaseMusic并不支持监听IPv6。。
所以即使你打开了IPv6的端口，也无法连接。

**Comment by Koukotsukan** [comment]
好的，其实就是想让朋友也能用上，看来要考虑租一台国内的vps了，谢谢您！
